# Generated by Django 3.2.5 on 2022-01-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Oder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('telephone', models.CharField(max_length=50, verbose_name='联系电话')),
                ('car_number', models.CharField(max_length=50, verbose_name='车牌号')),
                ('appointment_date', models.DateTimeField(verbose_name='预计年审日期')),
                ('appointment_time', models.DateTimeField(verbose_name='预计车检时间')),
                ('visit', models.CharField(max_length=20, verbose_name='是否上门接车')),
                ('address', models.CharField(max_length=200, verbose_name='接车地点')),
            ],
            options={
                'verbose_name': '预约信息管理',
                'verbose_name_plural': '预约信息管理',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=11)),
                ('nickname', models.CharField(max_length=30)),
            ],
        ),
    ]
