# Generated by Django 3.2.5 on 2022-01-14 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder',
            name='appointment_date',
            field=models.CharField(max_length=50, verbose_name='预计年审日期'),
        ),
        migrations.AlterField(
            model_name='oder',
            name='appointment_time',
            field=models.CharField(max_length=50, verbose_name='预计车检时间'),
        ),
    ]
