# Generated by Django 3.2.5 on 2022-01-14 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220114_1827'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='oder',
            name='nickname',
        ),
    ]
