# Generated by Django 3.2.11 on 2022-01-17 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_oder_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='oder',
            name='type',
            field=models.IntegerField(choices=[(0, '未处理'), (1, '已处理')], default=0, verbose_name='处理状态'),
        ),
    ]
